# Generated by Django 3.1.7 on 2021-07-10 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('programs', multiselectfield.db.fields.MultiSelectField(choices=[('Bright Spark Education Program', 'Bright Spark Education Program'), ('Transformers (Livelihood)', 'Transformers (Livelihood)'), ('Feeding Program (Zero Hunger)', 'Feeding Program (Zero Hunger)'), ('Women of Courage (Gender)', 'Women of Courage (Gender)'), ('Youngistaan Animal Heroes', 'Youngistaan Animal Heroes'), ('Blood Donor', 'Blood Donor'), ('Others', 'Others')], max_length=157, null=True)),
                ('awards', models.ManyToManyField(blank=True, null=True, to='users.Award')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
